### ISSUE TITLE
No "add" icon

### ISSUE THREAD

**Issue by maodonovan** [cloudcell/pxWorks-MVP#1]
Once a new project has been created you add features using the "+" icon. I have installed pxWorks v0.12 on Ubuntu but don;t have a "+" icon. Rather an icon to "cleanup"  the project appears there instead. Is this an error or me?

![screenshot](https://user-images.githubusercontent.com/3115783/95382889-a0518a80-08ea-11eb-8c27-75aeba9e69c2.png)

**Comment by cloudcell** [comment]
You say that "Once a new project has been created you add features using the "+" icon." Where does it say that?
You have the right set of icons. As far as I see everything works correctly.
Feel free to join the pxworks channel at https://t.me/pxworks and I will guide you through.

**Comment by maodonovan** [comment]
Thanks for the response - I will join you on the channel. 

Regarding the comment add features using the "+" icon - I get that from https://www.pxworks.io/forum/main-forum/getting-started/ where is says ....

Adding a Code Block

To add a block on the canvas, click on the "+" icon. A library window should appear with a list of available blocks. Select a block which you want to be added. Move it on the canvas to where you want. Add a second block in the same manner and connect 'outputs' of one block to 'inputs' of blocks that are going to use the data that the first block produces.

**Comment by cloudcell** [comment]
Thank you very much maodonovan, I fixed that text. It referred to an old version of the interface.
